import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/ui/molecules/Navbar";
import { SectionWrapper } from "@/ui/atoms/SectionWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Next14Masters demo",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className} suppressHydrationWarning={true}>
				<Navbar />
				<SectionWrapper className="py-12">{children}</SectionWrapper>
			</body>
		</html>
	);
}
