import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import { Navbar } from "@/ui/molecules/Navbar";
import { Footer } from "@/ui/molecules/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Next14Masters demo",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={clsx("flex min-h-dvh flex-col", inter.className)}
				suppressHydrationWarning={true}
			>
				<Navbar />
				<main className="mx-auto w-full max-w-2xl px-8 py-12 md:max-w-4xl lg:max-w-7xl">
					{children}
				</main>
				<Footer />
			</body>
		</html>
	);
}
